name: Bootstrap examples
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout Repo
         uses: actions/checkout@v4
      -  name: Setup HTML
         uses: actions/setup-html@v4
         with:
           html-version: '3.10'
      -  name: Install Dependencies
         run: |
           git config user.name tkumaran-git
           git config user.email tkumaran66@outlook.com
           git add .
           git commit -m "Modified code feed"
           git push
